### ISSUE TITLE
Reduce 3-SAT to CircuitSAT

### ISSUE THREAD

**Issue by GiggleLiu** [GiggleLiu/ProblemReductions.jl#10]

**Comment by GiggleLiu** [comment]
Ref: https://github.com/GiggleLiu/ScientificComputingDemos/tree/main/Spinglass/src

**Comment by SciCodePhy** [comment]
Reduce 3-SAT to QUBO (Under Development)

## I. Quadratic Unconstrained Binary Optimizati (QUBO)

The QUBO problem is to minimize or maximize a quadratic form $y=x^T Q x$, where $x$ is a Boolean vector and $Q$ is a real square matrix.

## II. Transformation

Ref. 1 gives a new transformation from 3-SAT to QUBO:

1. Energy of an assignment $\vec{x}$ of a 3-SAT CNF in $Q$: We can introduce some dummy variables $\vec{a}$ and define a new Boolean vector $\tilde{x}=\vec{x} \otimes \vec{a}$. The energy of an assignment $\vec{x}$ is defined as: $\min_{\vec{a}} \tilde{x}^T Q \tilde{x}$.
2. Clause QUBO: Given a clause $C$ of a 3-SAT instance. A QUBO is a clause QUBO (in terms of $C$) if: 1) The assignments satisfying $C$ has the minimal degenerate energy; 2) Assignments not satisfying $C$ have higher energy.
3. The remaing proof is lengthy. One may check Ref. 1 for more details.

## III. References

1. https://arxiv.org/pdf/2305.02659
2. https://arxiv.org/pdf/1811.11538

# Reduce QUBO to Spin Glass

For a given graph $G=(V,E)$, we can define a classical spin model:

$$
H=\sum_{(i, j) \in E} J_{i j} \sigma_i \sigma_j+\sum_{i \in V} h_i \sigma_i
$$

I don't find good references for this reduction, but it seems that this reduction is trivial:

* $J_{ij} \rightarrow Q_{ij}$
* $h_i \rightarrow 0$
* Therefore, QUBO can be trivially transformed to solving the ground state of a spin glass model.

**Comment by GiggleLiu** [comment]
https://support.dwavesys.com/hc/en-us/community/posts/1500000470701-What-are-the-cost-function-for-NAND-and-NOR-gates

**Comment by SciCodePhy** [comment]
Solved: Reduction from SAT to Circuit SAT constructed.
