### ISSUE TITLE
Reduce 3-SAT to independent set problems

### ISSUE THREAD

**Issue by GiggleLiu** [GiggleLiu/ProblemReductions.jl#11]

**Comment by SciCodePhy** [comment]
# Reduce 3-SAT to Independent SAT Problem

## I. Definitions and Background

### I-A. SAT

* Boolean Algebra [see 'Reduce k-SAT to 3-SAR' issue]
* Cook-Levin Theorem: 3-SAT is NP-complete.

### I-B. Independent Set Problem (IS)

* Independent Set: For an undirected graph $G$ and its subset $S \subset G $, $S$ is independent if all the vertices in $S$ cannot be connected by edges (aka: not adjacent).
* Independent Set Problem: Given a graph $G$ and an integer $k$, check whether $G$ has an independent set of size $k$.

## II. Proof (3-SAT <= IS)

We can translate an arbitrary 3-SAT CNF (an instance of 3-SAT) to an graph $G$ associated with $k$ (an instance of IS) [Ref. 2].

* Step-0: The number of clauses in this CNF corresponds to $k$.
* Step-1: The new graph $G$ will have 2$n$ vertices (all the $n$ literals and their negations).
* Step-2: For each clause such as $x_1 \lor x_2 \lor x_3$, we connect edges between all these three vertices.
* Step-3: We connect all the literals to their negations.

It can proven that:

* This CNF is satisfiable if and only if the generated $G$ has an independent set of size $k$.
* The generation of the new graph is within polynomial time.

## III. References

Core References:

1. The Nature of Computation
2. https://www.cs.umd.edu/class/fall2017/cmsc451-0101/Lects/lect20-np-3sat.pdf

Other References:

3. https://courses.engr.illinois.edu/cs374/fa2020/lec_prerec/23/23_2_0_0.pdf

**Comment by SciCodePhy** [comment]
Finished in #65
