### ISSUE TITLE
Reduce from cutting problem to/from spin-glass

### ISSUE THREAD

**Issue by GiggleLiu** [GiggleLiu/ProblemReductions.jl#13]

**Comment by c-allergic** [comment]
## Cutting problem
There are several different explanations of cutting. Here I'll just mention one of them.<br>

**Definition of "Maximum cut":**
- Given an undirected weighted graph, find a cut that allows the total weight of the edges cut to be the largest of all

 **Cut** here could means we divide the vertices into two different set, then the edges between any two vertices in those different set(if there exists) are cut down. Then we could calculate the total weight of the cut edges.
The function that the weight of the cut edges: 
  $$W =\sum_{(i,j)\epsilon{E}} W_{i,j} (x_i+x_j-2x_ix_j)$$ x<sub>i</sub> and x<sub>j</sub> here represents the binary varibles of the vertices, the function allows the weight is calculated if the two vertices are not in the same set.So basically we need to maximize this function.
  


## Spin Glass 
Here we only care about its energy function 
$$H = -\sum_{<i,j>} J_{ij}S_iS_j - \sum_{I}h_iS_i$$
$$H = \sum_{<i,j>} J_{ij}S_iS_j + \sum_{i}h_iS_i$$
Tips: The signature here depend on the condition of your problem. Basically they are the same.<br>
- J here means the interaction intensity between to spins in the system and the h here means the interaction intensity from onsite energy to the spins. 
- S here means the spinning direction of the spins.
- The basic rule:(based on the first function)
   1. When J is positive, the energy would be minimized if the spinning directions are aligned<br>
   2. When J is negative, the energy would be minimized if the spinning directions are anti-aligned
   3. When h>0(<0), the energy would be minimized if S=+1 (-1)

So different spins configuration would lead to the difference in the energy of the system. So most of the time we want to figure out the configuration that makes the energy of the system smallest.


## Reduce Spin Glass to/from Cutting problem
We notice that both of the problems have something to do with "minimum" or "maximum" (we have minimum cut as well as maximum cut) and the ralated functions look alike.So we want to map one of them to another.

### Spin Glass to Cutting Problem
Consider this function: 
$$H = -\sum_{<i,j>} J_{ij}S_iS_j - \sum_{i}h_iS_i$$
We could assign the binary values in the following rules:
```math
x= \begin{cases} 1 & \text{if } S_i =-1 \\ 0 & \text{if }S_i = 1 \\ \end{cases}
```
$$x=(1-S_i)/2$$
By doing so, we could represents an aligned spins by two vertices in the same set.
And we could map interaction intensity simply by the weight of edges:
$$W_{ij}=-J_{ij}$$
" **-** " here means that we are dealing with minimizing the energy function.<br>
For the onsite energy term, it's a little bit hard for me to understand so I'm not going to give some explanation here.
And so for the reverse mapping process.

**Comment by c-allergic** [comment]
Completed in #44 
Onsite energy term was not considered yet.
