### ISSUE TITLE
Decision: how to applied to reduction to constrained topology

### ISSUE THREAD

**Issue by GiggleLiu** [GiggleLiu/ProblemReductions.jl#19]
For example, we have the same problem defined on planar graph, unit-disk graph, tree graphs et al, instead of the most generic ones.

I suggest we define some wrapper types on the `SimpleGraph` type that defined in `Graphs.jl`.

Ref:
- https://github.com/QuEraComputing/UnitDiskMapping.jl

**Comment by hmyuuu** [comment]
It might be beneficial if we also wrap on `SimpleEdgeIter` type, and have`edges(g)` return an iterator. 

The point is that, we can check if an edge exists simply through a `has_edge` function without needing to generate all the edges again. c.f. [Graphs.jl/](https://github.com/JuliaGraphs/Graphs.jl/blob/master/src/SimpleGraphs/simpleedgeiter.jl#L119)
> in(e, es::SimpleEdgeIter) = has_edge(es.g, e)

e.g. in the case of  UnitDiskGraph, we can use
> Graphs.has_edge(g::UnitDiskGraph, s, d) = sum(abs2, g.locations[s] .- g.locations[d]) ≤ g.radius^2

**Comment by hmyuuu** [comment]
Here is some benchmarks on my device with #34
```julia
julia> g = UnitDiskGraph([(0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (1.0, 1.0)], 1.2)
UnitDiskGraph{2, Float64}([(0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (1.0, 1.0)], 1.2)

julia> e = Graphs.SimpleEdge((3,4))
Edge 3 => 4

julia> @btime e in edges(g)
  29.815 ns (1 allocation: 32 bytes)
true

julia> @btime e in ProblemReductions.all_edges(g)
  83.203 ns (2 allocations: 208 bytes)
true

julia> @btime collect(edges(g))
  107.245 ns (4 allocations: 368 bytes)
```
