### ISSUE TITLE
Variables Interface in SAT and Set Covering [Need to be discussed]

### ISSUE THREAD

**Issue by SciCodePhy** [GiggleLiu/ProblemReductions.jl#50]
`variables` functions in  `Satisfiability.jl`[@SciCodePhy #37 ] and `SetCovering.jl`[@c-allergic #39 ] are not consistent with #38 , which are required to generate from 1 to num_variables by #38 .

**Comment by GiggleLiu** [comment]
Decision: variables can be any vector like object.
