### ISSUE TITLE
potential problems in SpinGlass.jl

### ISSUE THREAD

**Issue by c-allergic** [GiggleLiu/ProblemReductions.jl#60]
First I initialize a spinglass problem using the construct function of this struct
```
g2 = HyperGraph(4, [[1, 2], [1], [2,3], [2]])
sg = SpinGlass(g2, [1, 2, 1, -1])
```
then I use `findbest` to find the best config
```
findbest(sg,BruteForce())
```
output:
```
2-element Vector{Vector{Int64}}:
 [1, 0, 1, 0]
 [1, 0, 1, 1]
```
That's was weird, because there are actually 3 variables in the problem but if a use the construct function to initialize the problem, the variables would become 4. And the output config wouldn't reflect the real config.

**Comment by GiggleLiu** [comment]
It is not a bug. The correct way of declaring a 3-vertex hypergraph is as follows.
```julia
julia> using ProblemReductions

julia> g2 = HyperGraph(3, [[1, 2], [1], [2,3], [2]])   # the first argument should be 3
HyperGraph(3, [[1, 2], [1], [2, 3], [2]])

julia> sg = SpinGlass(g2, [1, 2, 1, -1])
SpinGlass{HyperGraph, Vector{Int64}}(HyperGraph(3, [[1, 2], [1], [2, 3], [2]]), [1, 2, 1, -1])

julia> findbest(sg,BruteForce())
1-element Vector{Vector{Int64}}:
 [1, 0, 1]
```
